version: '3.1'
services:
  stats-server:
    build: ./stats/stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING.DATASOURCE.USERNAME=yoda
      - SPRING.DATASOURCE.PASSWORD=123


  stats-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=yoda
      - POSTGRES_PASSWORD=123


  ewm-service:
    build: ./ewm-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING.DATASOURCE.USERNAME=yoda
      - SPRING.DATASOURCE.PASSWORD=123
    image: ewm_service
    container_name: ewm-service

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=yoda
      - POSTGRES_PASSWORD=123