version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    restart: always
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=yoda
      - POSTGRES_PASSWORD=123


  stats-server:
    build: ./stats/stats-service
    image: stats_service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=yoda
      - POSTGRES_PASSWORD=123